#!/bin/sh

ARCHITECTURE=`uname`
TOOLS_DIR=$NLSTOOLS

for FILE in */*.sav
do
    PROGRAM=`echo $FILE | cut -d'/' -f1`
    echo installing $PROGRAM
    /bin/cp -p $PROGRAM/$PROGRAM.BINARY.Linux $PROGRAM/$PROGRAM.sav $NLSTOOLS/$PROGRAM
done
