#!/bin/sh

# ARCHITECTURE=`uname`

SRC_HOME=""
if [ $# -gt 0 ] 
then
   if [ $1 = "-H" ]
   then
      SRC_HOME="-H"
      shift
   fi
fi


if [ $# -gt 0 ]
then
   TOOLS_DIR=$1
else
   TOOLS_DIR=$HOME/specialist/SKR/tools
fi

cd $TOOLS_DIR

# MAKE_DIRS=`find . -name loader.pl | sed -e 's/loader.pl//' | sed -e 's/[./]//g' | sort`
# We no longer use the original Prolog versions of
# build_ambig_examples, extract_mrconso_sources, flip_variants,
# glean_ambig, mm_tokenizer, or prefilter_mrconso

MAKE_DIRS="conv_lex filter_mrconso glean_mrconso mm_print mm_variants"

COUNT=`echo $MAKE_DIRS | wc -w`

echo making in $COUNT dirs: $MAKE_DIRS


for APP_DIR in $MAKE_DIRS
do
   cd $APP_DIR
   # PROGRAM=`echo $APP_DIR | sed -e 's@[./]@@g'`
   PROGRAM=$APP_DIR
   echo '################################################################'
   /bin/rm -f $PROGRAM $PROGRAM.sav $PROGRAM.BINARY.Linux $PROGRAM.sav $PROGRAM.BINARY.Linux
   echo running xref in directory $APP_DIR
   echo '################################################################'
   echo y | SKRenv.16 spxref -R loader -i ~/sicstus.ini -x xref -u undef -w warning -m module; echo; echo UNDEF:; cat undef
   echo making in directory $TOOLS_DIR/$APP_DIR:
   COMMAND="linkSICStus $SRC_HOME -PC -O $PROGRAM.BINARY.Linux -T $PROGRAM.sav"
   echo $COMMAND
   echo '################################################################'
   $COMMAND
   echo '################################################################'
   cd ..
done

wait

echo ALL DONE
