#!/bin/sh

ARCHITECTURE=`uname`

cd $HOME/specialist/SKR/tools

MAKE_DIRS=`find . -name loader.pl | sed -e 's/loader.pl//' | sed -e 's/[./]//g' | sort`

for DIR in $MAKE_DIRS
do
   cd $DIR
   # PROGRAM=`echo $DIR | sed -e 's@[./]@@g'`
   PROGRAM=$DIR
   echo '################################################################'
   /bin/rm -f $PROGRAM $PROGRAM.sav $PROGRAM.BINARY.Linux
   echo running xref in directory $DIR
   echo '################################################################'
   echo y | SKRenv.12 spxref -R loader -i ~/sicstus.ini -x xref -u undef -w warning -m module; echo; echo UNDEF:; cat undef
   echo making in directory $DIR:
   COMMAND="linkSICStus -P -O $PROGRAM.BINARY.Linux -T $PROGRAM.sav"
   echo $COMMAND
   echo '################################################################'
   $COMMAND
   echo '################################################################'
   cd ..
done

wait

echo ALL DONE
